version: '0.1.1-beta-{build}'
configuration:
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build ".\NetCoreTeamCity" -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack ".\NetCoreTeamCity" -c %CONFIGURATION% --no-build -o artifacts
test_script:
- dotnet test ".\NetCoreTeamCity.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
deploy:
  provider: NuGet
  api_key:
    secure: Fec5HdqiA0Akjsvv03vBNhcc1bSEtrOBNfLTcP5tL6LM/s++ra9EltKovDC3Mn3x
  skip_symbols: false
  artifact: /.*\.nupkg/
